export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'

export const GET_MEDICINE ="GET_MEDICINE"

export const POST_MEDICINE ="POST_MEDICINE"

export const LOADING_MEDICINE ="LOADING_MEDICINE"

export const ERROR_MEDICINE ="ERROR_MEDICINE"
